### ISSUE TITLE
 Web vault is not found

### ISSUE THREAD

**Issue by albebert** [MrMEEE/bitwarden_rs_rpm#10]
Hello, tanks for your work, 

i try to install bitwarden, but i got an error about web vault : 

```
Apr 22 15:20:44 bitwarden bitwarden_rs: [2020-04-22 15:20:44][bitwarden_rs][ERROR] Web vault is not found. To install it, please follow the steps in:
Apr 22 15:20:44 bitwarden bitwarden_rs: [2020-04-22 15:20:44][bitwarden_rs][ERROR] https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary#install-the-web-vault
Apr 22 15:20:44 bitwarden bitwarden_rs: [2020-04-22 15:20:44][bitwarden_rs][ERROR] You can also set the environment variable 'WEB_VAULT_ENABLED=false' to disable it
```

any idea ? thanks

**Comment by ssttkk** [comment]
I just installed it and had the same issue. I changed the `WEB_VAULT_FOLDER` path in `/etc/bitwarden_rs/bitwarden_rs.conf` from `/opt/bitwarden_rs/web/` to `/opt/bitwarden_rs/web/web-vault/` and it seems to be working.

**Comment by albebert** [comment]
Thanks for the tricks ! 

now it's working.

but i don't know how to access to the web vault right now

**Comment by ssttkk** [comment]
I'd say you can probably find it at `http://<your_server_ip>:8000`, at least that's where it was for me.

**Comment by albebert** [comment]
http://server:8000/admin 
all seems to be OK !

**Comment by ajostergaard** [comment]
@albebert might be helpful to the maintainer if you were to close this issue... :)

**Comment by albebert** [comment]
> 
> 
> @albebert might be helpful to the maintainer if you were to close this issue... :)

you are right !
